{
  "updates": [
    {
      "directory": "/",
      "groups": {"version-updates": {"patterns": ["*"]}},
      "package-ecosystem": "github-actions",
      "schedule": {"interval": "weekly"}
    }
  ],
  "version": 2
}
