# Copyright (c) 2024, Pecunia Project. All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; version 2 of the
# License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301  USA

name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install semantic-release
        run: npm install --global @semantic-release/exec semantic-release

      - name: Determine version
        run: semantic-release --dry-run

      - name: Build Pecunia
        uses: ./.github/actions/build
        with:
          version: ${{ env.MARKETING_VERSION }}

      - name: Create release
        run: semantic-release
